language: rust
sudo: false

cache:
  directories:
      - target

rust:
  - stable
  - nightly
  - beta

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build $FEATURES &&
      travis-cargo test $FEATURES &&
      travis-cargo doc $FEATURES &&
      echo "Testing README" &&
      rustdoc --test README.md -L dependency=./target/debug/deps --extern nickel=./target/debug/libnickel.rlib

after_success:
  - |
      (echo "docs.nickel.rs" > target/doc/CNAME) &&
      travis-cargo --only stable doc-upload

env:
  global:
    secure: nPXTdkq9TK4LmqJWqB4jxscDG1mnqJzO0UX5ni+oC0SohjgBxdWjbvJ8Kthk3c8Qg/2zGlCryuT1lV4TcD3jF86MHlRlXsO3G8fCbEGdLLzppbV0A2VnEw1knhv2mfUhxA8hsFJE2ncT5qeOVyQ6N3PAMGoYkdhhbD9N/9EWuqs=
  matrix:
    # travis-cargo requires prefixing additional args with --
    - FEATURES=""
    - FEATURES="-- --features ssl"
    - FEATURES="-- --features session"
    - FEATURES="-- --features secure_cookies"
    - FEATURES="-- --no-default-features"
